//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bank_system.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int IDContract { get; set; }
        public string NumberAccount { get; set; }
        public int UserID { get; set; }
        public double Amount { get; set; }
        public int Period { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public double Percent { get; set; }
    
        public virtual User User { get; set; }
    }
}
